apiVersion: skaffold/v4beta1
kind: Config
metadata:
    name: blog
build:
    local:
        push: false
    artifacts:
        - image: codyle212/client
          context: client
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: 'src/**/*.js'
                    dest: .
        - image: codyle212/comments
          context: comments
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: '*.js'
                    dest: .
        - image: codyle212/event-bus
          context: event-bus
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: '*.js'
                    dest: .
        - image: codyle212/moderation
          context: moderation
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: '*.js'
                    dest: .
        - image: codyle212/posts
          context: posts
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: '*.js'
                    dest: .
        - image: codyle212/query
          context: query
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: '*.js'
                    dest: .
deploy:
    kubectl: {}
manifests:
    rawYaml:
        - infrastructure/kubernetes/client-deployment.yaml
        - infrastructure/kubernetes/comments-deployment.yaml
        - infrastructure/kubernetes/event-bus-deployment.yaml
        - infrastructure/kubernetes/ingress-service.yaml
        - infrastructure/kubernetes/moderation-deployment.yaml
        - infrastructure/kubernetes/posts-deployment.yaml
        - infrastructure/kubernetes/query-deployment.yaml
